---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: concourse
  namespace: concourse
spec:
  secretName: concourse-tls
  dnsNames:
    - ci.a13s.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: concourse-headers
  namespace: concourse
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concourse
  namespace: concourse
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: concourse-concourse-headers@kubernetescrd
spec:
  tls:
    - hosts:
        - ci.a13s.io
      secretName: concourse-tls
  rules:
    - host: ci.a13s.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concourse-web
                port:
                  number: 8080
