resources:
  - name: pleiades
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.com:anthropos-labs/pleiades.git
      private_key: ((git.private_key))
      branch: mainline
  - name: ci-image
    type: registry-image
    icon: docker
    source:
      repository: registry.gitlab.com/anthropos-labs/pleiades/ci
      tag: latest
      username: ((registry.username))
      password: ((registry.password))

jobs:
  - name: set-pipeline
    serial: true
    plan:
      - get: pleiades
        trigger: true
      - set_pipeline: self
        file: pleiades/ci/pipelines/images.yaml
  - name: build-ci-image
    serial: true
    plan:
      - get: pleiades
        trigger: true
        passed:
          - set-pipeline
      - task: build
        privileged: true
        file: pleiades/ci/tasks/build-ci-image.yaml
      - put: ci-image
        params:
          image: image/image.tar
  - name: verify-gitpod-image
    serial: true
    plan:
      - get: pleiades
        trigger: true
        passed:
          - set-pipeline
      - task: build
        privileged: true
        file: pleiades/ci/tasks/build-gitpod-image.yaml
