resources:
  - name: pleiades
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.com:anthropos-labs/pleiades.git
      private_key: ((git.private_key))
      branch: mainline

jobs:
  - name: set-pipeline
    plan:
      - get: pleiades
        trigger: true
      - set_pipeline: self
        file: pleiades/ci/pipelines.yaml
  - name: build
    plan:
      - get: pleiades
        trigger: true
        passed:
          - set-pipeline
      - across:
          - var: go-versions
            values: [ "1.18.0", "1.18.1", "1.18.2", "1.18.3", "1.18.4" ]
            max_in_flight: 2
        do:
          - task: vet
            file: pleiades/ci/tasks/mage-cmd.yaml
            vars:
              cmd: "build:vet"
              username: ((registry.username))
              password: ((registry.password))
          - task: compile
            file: pleiades/ci/tasks/mage-cmd.yaml
            vars:
              cmd: "build:compile"
              username: ((registry.username))
              password: ((registry.password))
          - task: test
            file: pleiades/ci/tasks/mage-cmd.yaml
            vars:
              cmd: "build:test"
              username: ((registry.username))
              password: ((registry.password))
  - name: deploy-minio
    plan:
      - get: pleiades
        trigger: true
        passed:
          - set-pipeline
      - task: deploy
        file: pleiades/ci/tasks/deploy-minio.yaml
  - name: generate-binary
    plan:
      - get: pleiades
        trigger: true
        passed:
          - build
          - build-ci-image
      - task: build-binary
        file: pleiades/ci/tasks/mage-cmd.yaml
        vars:
          cmd: "build:compile"
