variables:
  GO_VERSION: "1.19"
  MAGE_VERSION: "1.13.0"

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test

.before_script_template: &build-test-scripts
  before_script:
    - ci/scripts/install-mage.sh
    - mage install:godeps

build:
  stage: build
  image: "golang:$GO_VERSION"
  <<: *build-test-scripts
  script:
    - |
      mage build:compile
  artifacts:
    paths:
      - "build/pleiades"
    name: "pleiades"
    expire_in: "5 days"
  rules:
    - if: '$BUILD_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

code_quality:
  rules:
    - if: $CODE_QUALITY_DISABLED
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Run code quality job in merge request pipelines
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH      # Run code quality job in pipelines on the default branch (but not in other branch pipelines)
    - if: $CI_COMMIT_TAG   

test:
  stage: test
  image: "golang:$GO_VERSION"
  <<: *build-test-scripts
  script:
    - go test -v ./... -coverprofile=coverage.txt -covermode atomic
    - gotestsum --junitfile report.xml --format testname
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
