apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ required  "The disk size is required" .Values.pleiades.storage.size }}
  storageClassName: {{ required  "The storage class is required" .Values.pleiades.storage.storageClass }}
