apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.pleiades.server.ports.http | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.pleiades.server.ports.raft | default 8081 }}
      targetPort: fabric
      protocol: TCP
      name: fabric
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-fabric
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.pleiades.server.ports.raft | default 8081 }}
    targetPort: fabric
    protocol: TCP
    name: fabric
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
