apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.pleiades.server.ports.http | default 8080 }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.pleiades.server.ports.raft | default 8081 }}
      targetPort: raft
      protocol: TCP
      name: raft
    - port: {{ .Values.pleiades.server.ports.gossip | default 8082 }}
      targetPort: serf
      protocol: TCP
      name: gossip
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
