kind: ConfigMap
metadata:
  name: grafana-agent-logs
apiVersion: host
data:
  agent.yaml: |
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: cloud
      configs:
      - name: integrations
        remote_write:
        - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
          basic_auth:
            username: 468612
            password: eyJrIjoiNWU3ZGMwNDgyZGMzYmVlM2YxY2MwY2I1ZjMwNzI5Yzg2OTRiZWJjMiIsIm4iOiJzdGFjay0zODQwMjAtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjY2NDY2Nn0=
    integrations:
      prometheus_remote_write:
      - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
        basic_auth:
          username: 468612
          password: eyJrIjoiNWU3ZGMwNDgyZGMzYmVlM2YxY2MwY2I1ZjMwNzI5Yzg2OTRiZWJjMiIsIm4iOiJzdGFjay0zODQwMjAtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjY2NDY2Nn0=
    
    
    logs:
      configs:
      - name: integrations
        clients:
        - url: https://logs-prod3.grafana.net/loki/api/config/push
          basic_auth:
            username: 233276
            password: eyJrIjoiNWU3ZGMwNDgyZGMzYmVlM2YxY2MwY2I1ZjMwNzI5Yzg2OTRiZWJjMiIsIm4iOiJzdGFjay0zODQwMjAtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjY2NDY2Nn0=
          external_labels:
            cluster: cloud
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
        scrape_configs:
        - job_name: integrations/kubernetes/pod-logs
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - cri: {}
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: __host__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_name
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
