---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: listener-80
  namespace: emissary
spec:
  port: 8080
  protocol: HTTP
  securityModel: INSECURE
  l7Depth: 0
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: listener-443
  namespace: emissary
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  l7Depth: 0
  hostBinding:
    namespace:
      from: ALL
