---
platform: linux
inputs:
  - name: pleiades
image_resource:
  type: registry-image
  source:
    repository: golang
    tag: ((.:go-versions))
run:
  path: /bin/sh
  args:
    - -c
    - |
      cd pleiades
      go build ./...
