---
platform: linux
inputs:
  - name: pleiades
image_resource:
  type: registry-image
  source:
    repository: golang
    tag: ((.:go-versions))
run:
  path: /bin/sh
  args:
    - -c
    - |
      cd pleiades
      mkdir bin
      export SHA=$(git rev-parse --short HEAD)
      go build \
        -ldflags "-X pkg.Sha=${SHA} -X pkg.GoVersion=$(go version) -X pkg.Version='22.6.30-dev.1'" \
        -o bin/pleiades-"${SHA}"
        main.go
