---
platform: linux
inputs:
  - name: pleiades
outputs:
  - name: binary
    path: pleiades/bin
image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest
run:
  path: ci/scripts/generate-binary.sh
  dir: pleiades
