---
platform: linux
inputs:
  - name: pleiades
outputs:
  - name: binary
    path: pleiades/bin
image_resource:
  repository: registry.gitlab.com/anthropos-labs/pleiades/ci
  tag: latest
  username: ((registry.username))
  password: ((registry.password))
params:
  MAGE_COMMAND: ((cmd))
run:
  path: ci/scripts/run-mage.sh
  dir: pleiades
