---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s3
  namespace: s3
spec:
  secretName: s3-tls
  dnsNames:
    - s3.r3t.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: s3-headers
  namespace: s3
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3
  namespace: s3
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: s3-s3-headers@kubernetescrd
spec:
  tls:
    - hosts:
        - s3.r3t.io
      secretName: s3-tls
  rules:
    - host: s3.r3t.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concourse-web
                port:
                  number: 9000
