resources:
  - name: pleiades
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.com:mxplusb/pleiades.git
      private_key: ((git.private_key))
      branch: mainline

jobs:
  - name: build
    plan:
      - get: pleiades
        trigger: true
      - across:
          - var: version
            values: [ "1.18.0", "1.18.1", "1.18.2", "1.18.3" ]
            max_in_flight: 5
        do:
          - task: vet
            file: pleiades/ci/tasks/go-lint.yaml
          - task: compile
            file: pleiades/ci/tasks/go-build.yaml
          - task: test
            file: pleiades/ci/tasks/go-test.yaml
