---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sally
  namespace: sally
  labels:
    app: sally
spec:
  replicas: 1
  template:
    metadata:
      name: sally
      labels:
        app: sally
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: sally
          image: registry.gitlab.com/anthropos-labs/pleiades/sally
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
      restartPolicy: Always
  selector:
    matchLabels:
      app: sally
---
apiVersion: v1
kind: Service
metadata:
  name: sally
  namespace: sally
spec:
  selector:
    app: sally
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sally
  namespace: sally
spec:
  secretName: sally-tls
  dnsNames:
    - a13s.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sally
  namespace: sally
spec:
  tls:
    - hosts:
        - a13s.io
      secretName: sally-tls
  rules:
    - host: a13s.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sally
                port:
                  number: 8080
