stages:
  - build
  - release

lint:
  stage: build
  image: registry.gitlab.com/anthropos-labs/api/builder:latest
  script:
    - buf lint
    - buf breaking --against "https://gitlab.com/anthropos-labs/api.git#branch=mainline"

docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination registry.gitlab.com/anthropos-labs/api/builder:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - Dockerfile
      allow_failure: true

upload:
  stage: release
  image: registry.gitlab.com/anthropos-labs/api/builder:latest
  variables:
    BUF_USER: sienna-al
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
  script:
    - |
      for f in databaseapi errorapi raftapi; do
        pushd $f
        buf push
        popd
      done
