name: Pull Request

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v2
      - name: Cache bazel build results
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-master
      - name: Build the code
        run: bazel build //...

      - name: Test the code
        run: bazel test //...
