name: Build & Test

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, ubuntu-22.04]
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-targets --all-features
      - run: cargo test --all-targets --all-features
