steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-go@v3
    with:
      go-version: '1.20'
      check-latest: true
      cache: true
  - name: build
    uses: magefile/mage-action@v2
    with:
      version: latest
      args: build:compile
