name: Pull Request

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v3
      - name: Cache Build Results
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-master
      - name: Build Pleiades
        run: bazel build //...

      - name: Test Pleiades
        run: bazel test //... --test_output=errors
