name: Build & Test

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, ubuntu-22.04]
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: install-stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --all-features
